import Head from "next/head";
import Image from "next/image";
import Script from "next/script";
import Header from "./components/common/Header";
import Footer from "./components/common/Footer";
import Breadcrumbs from "./components/common/Breadcrumbs";
import { useSelector } from "react-redux";

export default function Checkout() {
  const cartProducts = useSelector((state) => state.cart.carts.cart);
  const cartSummary = useSelector((state) => state.cart.carts.cartSummary);
  console.log(cartSummary, "hi");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="page-wrapper">
        <Header />

        <main className="main">
          <Breadcrumbs />

          <div className="page-content">
            <div className="checkout">
              <div className="container">
                <div className="checkout-discount">
                  <form action="#">
                    <input
                      type="text"
                      className="form-control"
                      required
                      id="checkout-discount-input"
                    />
                    <label
                      for="checkout-discount-input"
                      className="text-truncate"
                    >
                      Have a coupon? <span>Click here to enter your code</span>
                    </label>
                  </form>
                </div>
                <form action="#">
                  <div className="row">
                    <div className="col-lg-9">
                      <h2 className="checkout-title">Billing Details</h2>
                      <div className="row">
                        <div className="col-sm-6">
                          <label>Full Name *</label>
                          <input
                            type="text"
                            className="form-control"
                            required
                          />
                        </div>

                        <div className="col-sm-6">
                          <label>Phone *</label>
                          <input type="tel" className="form-control" required />
                        </div>
                      </div>

                      <label>Street address *</label>
                      <input
                        type="text"
                        className="form-control"
                        placeholder="House number and Street name"
                        required
                      />
                      <input
                        type="text"
                        className="form-control"
                        placeholder="Appartments, suite, unit etc ..."
                        required
                      />

                      <div className="row">
                        <div className="col-sm-6">
                          <label>City *</label>
                          <input
                            type="text"
                            className="form-control"
                            required
                          />
                        </div>

                        <div className="col-sm-6">
                          <label>State *</label>
                          <input
                            type="text"
                            className="form-control"
                            required
                          />
                        </div>
                      </div>

                      <div className="row">
                        <div className="col-sm-6">
                          <label>Postcode *</label>
                          <input
                            type="text"
                            className="form-control"
                            required
                          />
                        </div>
                        <div className="col-sm-6">
                          <label>Country *</label>
                          <input
                            type="text"
                            className="form-control"
                            required
                          />
                        </div>
                      </div>

                      <label>Email address *</label>
                      <input type="email" className="form-control" required />

                      <div className="custom-control custom-checkbox">
                        <input
                          type="checkbox"
                          className="custom-control-input"
                          id="checkout-create-acc"
                        />
                        <label
                          className="custom-control-label"
                          for="checkout-create-acc"
                        >
                          Create an account?
                        </label>
                      </div>

                      <div className="custom-control custom-checkbox">
                        <input
                          type="checkbox"
                          className="custom-control-input"
                          id="checkout-diff-address"
                        />
                        <label
                          className="custom-control-label"
                          for="checkout-diff-address"
                        >
                          Ship to a different address?
                        </label>
                      </div>

                      <label>Order notes (optional)</label>
                      <textarea
                        className="form-control"
                        cols="30"
                        rows="4"
                        placeholder="Notes about your order, e.g. special notes for delivery"
                      ></textarea>
                    </div>
                    <aside className="col-lg-3">
                      <div className="summary">
                        <h3 className="summary-title">Your Order</h3>

                        <table className="table table-summary">
                          <thead>
                            <tr>
                              <th>Product</th>
                              <th>Total</th>
                            </tr>
                          </thead>

                          <tbody>
                            {cartProducts?.length > 0 &&
                              cartProducts?.map((product) => {
                                return (
                                  <tr key={product?.id}>
                                    <td>
                                      <a href="#">{product?.name}</a>
                                    </td>
                                    <td>
                                      <div
                                        className={`product-price justify-content-end`}
                                      >
                                        {!product?.salePrice
                                          ? `$${
                                              product?.price * product?.quantity
                                            }`
                                          : `$${
                                              product?.salePrice *
                                              product?.quantity
                                            }`}
                                      </div>
                                    </td>
                                  </tr>
                                );
                              })}

                            <tr className="summary-subtotal">
                              <td>Subtotal:</td>
                              <td>${cartSummary.subtotal}</td>
                            </tr>
                            {cartSummary?.subtotal < 500 ? (
                              <tr className="summary-shipping-row">
                                <td>
                                  <div className="custom-control custom-radio pl-0">
                                    <label>Flat Shipping</label>
                                  </div>
                                </td>
                                <td>${cartSummary?.shipping}</td>
                              </tr>
                            ) : (
                              <tr className="summary-shipping-row">
                                <td>
                                  <div className="custom-control custom-radio pl-0">
                                    <label
                                      className="free-shipping"
                                      htmlFor="free-shipping"
                                    >
                                      Free Shipping
                                    </label>
                                  </div>
                                </td>
                                <td className="free-shipping">$0</td>
                              </tr>
                            )}
                            <tr className="summary-shipping-row">
                              <td>Tax:</td>
                              <td>${cartSummary?.tax}</td>
                            </tr>
                            <tr className="summary-total">
                              <td>Total:</td>
                              <td>${cartSummary?.grandTotal}</td>
                            </tr>
                          </tbody>
                        </table>

                        <div
                          className="accordion-summary"
                          id="accordion-payment"
                        >
                          <div className="card">
                            <div className="card-header" id="heading-3">
                              <h2 className="card-title">
                                <a
                                  className="collapsed"
                                  role="button"
                                  data-toggle="collapse"
                                  href="#collapse-3"
                                  aria-expanded="false"
                                  aria-controls="collapse-3"
                                >
                                  Cash on delivery
                                </a>
                              </h2>
                            </div>
                            <div
                              id="collapse-3"
                              className="collapse"
                              aria-labelledby="heading-3"
                              data-parent="#accordion-payment"
                            >
                              <div className="card-body">
                                Quisque volutpat mattis eros. Lorem ipsum dolor
                                sit amet, consectetuer adipiscing elit. Donec
                                odio. Quisque volutpat mattis eros.
                              </div>
                            </div>
                          </div>

                          <div className="card">
                            <div className="card-header" id="heading-1">
                              <h2 className="card-title">
                                <a
                                  role="button"
                                  data-toggle="collapse"
                                  href="#collapse-1"
                                  aria-expanded="true"
                                  aria-controls="collapse-1"
                                >
                                  Direct bank transfer
                                </a>
                              </h2>
                            </div>
                            <div
                              id="collapse-1"
                              className="collapse show"
                              aria-labelledby="heading-1"
                              data-parent="#accordion-payment"
                            >
                              <div className="card-body">
                                Make your payment directly into our bank
                                account. Please use your Order ID as the payment
                                reference. Your order will not be shipped until
                                the funds have cleared in our account.
                              </div>
                            </div>
                          </div>

                          <div className="card">
                            <div className="card-header" id="heading-4">
                              <h2 className="card-title">
                                <a
                                  className="collapsed"
                                  role="button"
                                  data-toggle="collapse"
                                  href="#collapse-4"
                                  aria-expanded="false"
                                  aria-controls="collapse-4"
                                >
                                  PayPal{" "}
                                  <small className="float-right paypal-link">
                                    What is PayPal?
                                  </small>
                                </a>
                              </h2>
                            </div>
                            <div
                              id="collapse-4"
                              className="collapse"
                              aria-labelledby="heading-4"
                              data-parent="#accordion-payment"
                            >
                              <div className="card-body">
                                Nullam malesuada erat ut turpis. Suspendisse
                                urna nibh, viverra non, semper suscipit, posuere
                                a, pede. Donec nec justo eget felis facilisis
                                fermentum.
                              </div>
                            </div>
                          </div>

                          <div className="card">
                            <div className="card-header" id="heading-5">
                              <h2 className="card-title">
                                <a
                                  className="collapsed"
                                  role="button"
                                  data-toggle="collapse"
                                  href="#collapse-5"
                                  aria-expanded="false"
                                  aria-controls="collapse-5"
                                >
                                  Credit Card (Stripe)
                                  <Image
                                    src="/payments.png"
                                    width="100"
                                    height="100"
                                    alt="payments cards"
                                  />
                                </a>
                              </h2>
                            </div>
                            <div
                              id="collapse-5"
                              className="collapse"
                              aria-labelledby="heading-5"
                              data-parent="#accordion-payment"
                            >
                              <div className="card-body">
                                {" "}
                                Donec nec justo eget felis facilisis
                                fermentum.Lorem ipsum dolor sit amet,
                                consectetuer adipiscing elit. Donec odio.
                                Quisque volutpat mattis eros. Lorem ipsum dolor
                                sit ame.
                              </div>
                            </div>
                          </div>
                        </div>

                        <button
                          type="submit"
                          className="btn btn-outline-primary-2 btn-order btn-block"
                        >
                          <span className="btn-text">Place Order</span>
                          <span className="btn-hover-text">
                            Proceed to Checkout
                          </span>
                        </button>
                      </div>
                    </aside>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </main>
      </div>

      <Footer />

      <Script src="./scripts/jquery.min.js"></Script>
      <Script src="./scripts/bootstrap.bundle.min.js"></Script>
      <Script src="./scripts/jquery.hoverIntent.min.js"></Script>
      <Script src="./scripts/jquery.waypoints.min.js"></Script>
      <Script src="./scripts/superfish.min.js"></Script>
      <Script src="./scripts/owl.carousel.min.js"></Script>
      {/* <Script src="./scripts/wNumb.js"></Script> */}
      <Script src="./scripts/bootstrap-input-spinner.js"></Script>
      <Script src="./scripts/jquery.magnific-popup.min.js"></Script>
      {/* <Script src="./scripts/nouislider.min.js"></Script> */}
      <Script src="./scripts/main.js"></Script>
    </>
  );
}
