import Head from "next/head";
import Script from "next/script";
import Header from "./components/common/Header";
import Footer from "./components/common/Footer";
import ScrollToTop from "./components/common/ScrollToTop";
import { ToastContainer, toast } from "react-toastify";
import { useState } from "react";
import Link from "next/link";


export default function Error() {
    const [openModal, setOpenModal] = useState(false);
    const closeModalFn = () => {
        document.body.classList.remove('modal-open');
        document.body.classList.remove('adjust-padding');
        setOpenModal(false);
      };
    
      const openModalFn = () => {
        document.body.classList.add('modal-open');
        document.body.classList.add('adjust-padding');
        setOpenModal(true);
      };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="page-wrapper">
       
        <Header openModalFn={openModalFn} />

        <main className="main">
          {/* <ToastContainer /> */}
          
          <div className="error-content text-center" style={{"backgroundImage": "url(/error-bg.jpg)"}}>
            	<div className="container">
            		<h1 className="error-title">Error 404</h1>
            		<p>We are sorry, the page you've requested is not available.</p>
            		<Link href="/" className="btn btn-outline-primary-2 btn-minwidth-lg">
            			<span>BACK TO HOMEPAGE</span>
            			<i className="icon-long-arrow-right"></i>
            		</Link>
            	</div>
        	</div>
        </main>
      </div>
      <ScrollToTop />

      <Footer />
    
      <Script src="./scripts/jquery.min.js"></Script>
      <Script src="./scripts/bootstrap.bundle.min.js"></Script>
      <Script src="./scripts/jquery.hoverIntent.min.js"></Script>
      <Script src="./scripts/jquery.waypoints.min.js"></Script>
      <Script src="./scripts/superfish.min.js"></Script>
      <Script src="./scripts/owl.carousel.min.js"></Script>
      {/* <Script src="./scripts/wNumb.js"></Script> */}
      <Script src="./scripts/bootstrap-input-spinner.js"></Script>
      <Script src="./scripts/jquery.magnific-popup.min.js"></Script>
      {/* <Script src="./scripts/nouislider.min.js"></Script> */}
      <Script src="./scripts/main.js"></Script>
    </>
  );
}
