import Head from "next/head";
import Image from "next/image";
import Script from "next/script";
import Header from "./components/common/Header";
import Footer from "./components/common/Footer";
import Breadcrumbs from "./components/common/Breadcrumbs";
import { useDispatch, useSelector } from "react-redux";
import { useEffect, useState } from "react";
import NoContent from "./components/common/NoContent";
import { removeItemToWishlists } from "@/store/wishlistSlice";

export default function Wishlist() {
  const wishlist = useSelector((state) => state.wishlist.wishlist.wishlist);
  const products = useSelector((state) => state.products.products);
  const sizeChart = useSelector((state) => state.sizes.sizes);
  const [wishlistProducts, setWishlistProducts] = useState([]);

  const dispatch = useDispatch();

  useEffect(() => {
    if (typeof window !== undefined) {
      const userData = localStorage.getItem("data");
      if (userData) {
        // Get all the product ids from wishlist table so we can get the same products from products table below
        const wishlistProductIds = wishlist?.map((item) => item?.productId);
        const wishlistProducts = products?.filter((product) =>
          wishlistProductIds?.includes(product?.id)
        );
        setWishlistProducts(wishlistProducts);
      }
    }
  }, []);

  const removeProductFromWishlist = (productId) => {
    dispatch(removeItemToWishlists({ productId: productId }));
    let tr = document.querySelector(`table tbody tr[data-id="${productId}"]`);

    if (tr) {
      tr.remove();
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="page-wrapper">
        <Header />

        <main className="main">
          <Breadcrumbs />

          <div className="page-content">
            <div className="container">
              {wishlist?.length > 0 ? (
                <table className="table table-wishlist table-mobile">
                  <thead>
                    <tr>
                      <th>Product</th>
                      <th>Price</th>
                      <th>Stock Status</th>
                      <th></th>
                    </tr>
                  </thead>
                  <tbody>
                    {wishlistProducts?.length > 0 &&
                      wishlistProducts?.map((wishlist) => {
                        return (
                          <tr key={wishlist?.id} data-id={wishlist?.id}>
                            <td className="product-col">
                              <div className="product">
                                <figure className="product-media">
                                  <a href="#">
                                    <Image
                                      src={`/${wishlist?.image}`}
                                      alt="Product image"
                                      width="60"
                                      height="60"
                                    />
                                  </a>
                                </figure>
                                <div>
                                  <h3 className="product-title">
                                    <a href="#">{wishlist?.name}</a>
                                  </h3>
                                  <div className={`product-size mb-0`}>
                                    {sizeChart.length > 0 &&
                                      sizeChart?.map((size) => {
                                        return (
                                          <a
                                            title=""
                                            className={`text-uppercase ${
                                              wishlist?.size?.includes(
                                                size?.name
                                              )
                                                ? "active"
                                                : "disabled"
                                            }`}
                                            key={size?.name}
                                          >
                                            {size?.name}
                                          </a>
                                        );
                                      })}
                                  </div>
                                </div>
                              </div>
                            </td>
                            <td className="price-col">
                              <div className="product-price mb-0">
                              {
                                wishlist?.salePrice ?
                                <>
                               <div className="new-price">
                                  ${wishlist?.salePrice}
                               </div>
                               <div className="old-price">
                                  ${wishlist?.price}
                               </div>
                                </>
                               :
                                  `$${wishlist?.price}`
                              }
                              </div>
                            </td>
                            <td className="stock-col">
                              <span className="in-stock">{wishlist?.quantity>0 ? 'In stock':'Out of Stock'}</span>
                            </td>

                            <td className="remove-col">
                              <button
                                className="btn-remove"
                                onClick={() =>
                                  removeProductFromWishlist(wishlist?.id)
                                }
                              >
                                <i className="icon-close"></i>
                              </button>
                            </td>
                          </tr>
                        );
                      })}
                  </tbody>
                </table>
              ) : (
                <NoContent />
              )}
              {/* <div className="wishlist-share">
                <div className="social-icons social-icons-sm mb-2">
                  <label className="social-label">Share on:</label>
                  <a
                    href="#"
                    className="social-icon"
                    title="Facebook"
                    target="_blank"
                  >
                    <i className="icon-facebook-f"></i>
                  </a>
                  <a
                    href="#"
                    className="social-icon"
                    title="Twitter"
                    target="_blank"
                  >
                    <i className="icon-twitter"></i>
                  </a>
                  <a
                    href="#"
                    className="social-icon"
                    title="Instagram"
                    target="_blank"
                  >
                    <i className="icon-instagram"></i>
                  </a>
                  <a
                    href="#"
                    className="social-icon"
                    title="Youtube"
                    target="_blank"
                  >
                    <i className="icon-youtube"></i>
                  </a>
                  <a
                    href="#"
                    className="social-icon"
                    title="Pinterest"
                    target="_blank"
                  >
                    <i className="icon-pinterest"></i>
                  </a>
                </div>
              </div> */}
            </div>
          </div>
        </main>
      </div>
      <Footer />
      <Script src="./scripts/jquery.min.js"></Script>
      <Script src="./scripts/bootstrap.bundle.min.js"></Script>
      <Script src="./scripts/jquery.hoverIntent.min.js"></Script>
      <Script src="./scripts/jquery.waypoints.min.js"></Script>
      <Script src="./scripts/superfish.min.js"></Script>
      <Script src="./scripts/owl.carousel.min.js"></Script>
      <Script src="./scripts/wNumb.js"></Script>
      <Script src="./scripts/bootstrap-input-spinner.js"></Script>
      <Script src="./scripts/jquery.magnific-popup.min.js"></Script>
      <Script src="./scripts/nouislider.min.js"></Script>
      <Script src="./scripts/main.js"></Script>
    </>
  );
}
